# Daily Challenge

**The Power Of NumPy**

We said that NumPy is pretty much a list on steroids. Let’s see that in action.

For the tasks below, do them using a regular Python list implementation, and then use NumPy.

- Create a table (i.e. a 2d array) of size M x N filled with random integers between 1 and 100,
where 1 < N < 40 and 1 < M < 50.

- Print out the third row

- Print out the third column

- Set every element in the last row equal to 7

- Set every element in the last column equal the sum of the first two columns. (note: the result of
the sum is a list which will the same length as the last column)



In [4]:
import pandas as pd
import numpy as np
import random

## Using Python

In [7]:

N = random.randint(2,40)
M = random.randint(2,50)

py_table = []
for r in range(0, N):
    py_table.append([random.randint(1,100) for c in range(0, M)])
    
    
py_table

[[60,
  86,
  30,
  88,
  95,
  20,
  52,
  17,
  75,
  49,
  5,
  98,
  62,
  72,
  39,
  49,
  86,
  11,
  63,
  68,
  7,
  100,
  11,
  74,
  92,
  37,
  48],
 [44,
  81,
  89,
  31,
  24,
  84,
  46,
  67,
  22,
  21,
  78,
  1,
  57,
  65,
  82,
  86,
  82,
  47,
  49,
  16,
  34,
  8,
  83,
  55,
  36,
  59,
  75],
 [77,
  92,
  20,
  39,
  28,
  49,
  13,
  14,
  10,
  84,
  17,
  71,
  53,
  96,
  74,
  49,
  78,
  64,
  33,
  85,
  39,
  78,
  51,
  56,
  48,
  47,
  96],
 [37,
  86,
  15,
  71,
  29,
  24,
  75,
  28,
  4,
  35,
  7,
  3,
  91,
  90,
  77,
  80,
  34,
  41,
  6,
  11,
  5,
  87,
  28,
  89,
  36,
  26,
  58],
 [20,
  79,
  51,
  71,
  88,
  76,
  83,
  87,
  4,
  10,
  81,
  52,
  30,
  58,
  41,
  45,
  17,
  31,
  29,
  11,
  43,
  74,
  99,
  27,
  24,
  64,
  35],
 [19,
  32,
  34,
  62,
  80,
  24,
  49,
  73,
  37,
  80,
  22,
  84,
  37,
  81,
  17,
  17,
  64,
  22,
  22,
  91,
  60,
  94,
  19,
  3,
  92,
  65,
  27],
 [66,
  52,
  62,
  21,
  68,
  

In [14]:
len(py_table) == N

True

In [15]:
len(py_table[0])==M

True

In [16]:
# The third row
py_table[2]

[77,
 92,
 20,
 39,
 28,
 49,
 13,
 14,
 10,
 84,
 17,
 71,
 53,
 96,
 74,
 49,
 78,
 64,
 33,
 85,
 39,
 78,
 51,
 56,
 48,
 47,
 96]

In [21]:
#The third column
col = [py_table[i][2] for i in range(len(py_table))]
col

[30, 89, 20, 15, 51, 34, 62]

In [57]:
# Set every element in the last row equal to 7 (index)
seven = [py_table[len(py_table)-1][i] for i in range(len(py_table[len(py_table)-1])) if py_table[len(py_table)-1][i]==7]
seven

[]

In [58]:
# Set every element in the last column equal the sum of the first two columns
sum_list = [item1+item2 for item1,item2 in zip(py_table[0],py_table[1])]
element = {i for i in sum_list for j in py_table[len(py_table)-1] if i==j}
element

{58, 84, 94, 96, 98}

In [61]:
index = {j for i in range(len(sum_list)) for j in range(len(py_table[len(py_table)-1])) if sum_list[i]==py_table[len(py_table)-1][j]}
index

{5, 11, 23, 24, 26}

## Using Numpy

In [37]:
N = np.random.randint(2,40)
M = np.random.randint(2,50)
np_table = np.random.randint(1,100,(N,M))

In [38]:
np_table

array([[36, 97, 79, 67, 98,  2, 79, 25, 69, 84, 20, 91, 92, 73, 38, 66,
        49, 45, 25, 83, 50, 75, 85, 40, 93],
       [29, 21, 31, 42, 57, 38,  1, 53, 75, 91, 43, 41, 35, 73,  1, 36,
        97, 94, 10, 83, 77, 33, 17, 10, 81],
       [14, 10, 69, 48,  3, 35, 50, 48, 77, 29, 62,  2, 37, 72, 32,  8,
        29, 89, 19, 76, 78, 32, 22, 57, 10],
       [90,  2, 80, 12, 71, 94, 21, 12, 62, 66, 95, 33, 39, 94, 77, 85,
        14, 26, 49, 55, 82, 56, 24, 85, 80],
       [25, 58, 36, 48, 52, 94, 89, 70, 75, 71, 86, 42, 95, 85, 74, 97,
        18, 17, 57,  1, 75, 10, 71,  9, 53],
       [94,  5, 75, 22, 74, 54, 36, 69, 60, 99, 57,  8, 10, 73, 47, 73,
        77, 75, 22, 98, 54,  7, 17, 79, 68],
       [86, 89, 48, 63, 28, 87, 75, 99, 21, 34, 72,  1,  1, 72, 44, 38,
        74, 37, 49, 65, 43, 57, 14, 84, 59],
       [89, 70, 47, 64, 68, 34, 58, 10, 86, 99, 84, 82, 90, 53, 61, 62,
        37, 10, 68, 21, 86, 10, 55, 72, 45],
       [ 9,  3, 87, 55,  6, 61,  9, 65, 75, 85, 49, 18, 77, 73, 

In [39]:
# The third row
np_table[2]

array([14, 10, 69, 48,  3, 35, 50, 48, 77, 29, 62,  2, 37, 72, 32,  8, 29,
       89, 19, 76, 78, 32, 22, 57, 10])

In [40]:
# The third column
np_table[:,2]

array([79, 31, 69, 80, 36, 75, 48, 47, 87, 42, 33, 48, 55, 14, 29, 58, 79,
       97, 96, 59, 33, 11, 30, 54, 72,  9, 67, 13,  4,  1, 48,  5, 22])

In [51]:
# Set every element in the last row equal to 7
x = np_table[len(np_table)-1]
np.where(x==7)

(array([9], dtype=int64),)

In [64]:
# Set every element in the last column equal the sum of the first two columns
sum_rows = np_table[0]+np_table[1]
index2 = {j for i in range(len(sum_rows)) for j in range(len(np_table[len(np_table)-1])) if sum_rows[i]==np_table[len(py_table)-1][j]}
index2

{3, 19}