# Exercise XP NINJA


In [2]:
import pandas as pd
import numpy as np

In [66]:
a = np.arange(30)
b = a.reshape((5,6))
c = np.ones((5, 6, 3))

In [52]:
# a 5X6 matrix taken from c multiplied by a row vector taken from a (how many elements are in the vector)
new = c[:,:,0]*a[0:6]
new

array([[0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.],
       [0., 1., 2., 3., 4., 5.]])

In [53]:
new.shape

(5, 6)

In [56]:
# a 5x6 matrix taken from c multiplied by a column vector taken from a (how many elements are in the vector)
new_a = a.reshape(6,5)
new_a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [60]:
new2 = c[:,:,0]*new_a[:,0]
new2

array([[ 0.,  5., 10., 15., 20., 25.],
       [ 0.,  5., 10., 15., 20., 25.],
       [ 0.,  5., 10., 15., 20., 25.],
       [ 0.,  5., 10., 15., 20., 25.],
       [ 0.,  5., 10., 15., 20., 25.]])

In [61]:
new2.shape

(5, 6)

In [80]:
# a 6x3 matrix taken from b multiplied by c
new3 = b[0:6,0:3]*c[:,0:3,0]
new3

array([[ 0.,  1.,  2.],
       [ 6.,  7.,  8.],
       [12., 13., 14.],
       [18., 19., 20.],
       [24., 25., 26.]])

In [82]:
# a 5x6 matrix taken from b multiplied by c
new4 = b*c[:,:,0]
new4

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]])